<li class='col-4-1 not-animated' data-animate='fadeInUp'>
                      <div class="portfolio-img"><a href="[field:litpic/]" rel="imgZoom-group-252120" title="[field:title/]"><img src="[field:litpic/]" alt="[field:title/]"/><span class="opacity-overlay"><i class="icon-zoom"></i></span></a></div>
                      <div class="portfolio-title">
                        <h2><a href="images/1-1610201K6390-L.jpg" rel="imgZoom-group-title-252120" title="[field:title/]">[field:title/]</a></h2>
                      </div>
                    </li>