<div class="tab-box clearfix" style="display:block;">
                      <div id="a1portalSkin_ctr252102252102_TabList_QHDSPM252102M1334" class="tab-box-content"> <a name="26934" id="26934"></a>
                        <div class="module-default">
                          <div class="module-inner">
                            <div id="a1portalSkin_ctr252102252102_TabList_ctr252103252103_mainArea" class="module-content">
                              <div class="scrollable carousel clearfix">
                                <ul id="scrollable-252103" class="scrollable-default clearfix">
                                  {dede:arclist row='9' titlelen='36'}
                                  <li>
                                    <p><a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" alt="[field:title/]"/></a></p>
                                    <h2><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h2>
                                  </li>
                                  {/dede:arclist}
                                </ul>
                                <div class="carousel-direction"><a class="carousel-prev" id="carousel-prev-252103" href="javascript:;"><span><</span></a><a class="carousel-next" id="carousel-next-252103" href="javascript:;"><span>></span></a></div>
                              </div>
                              
                              <!-- E scrollable--><!-- End_Module_252103 --></div>
                          </div>
                        </div>
                      </div>
                      <p class="tab-more tab-more-center"><a href="/a/dianmianzhanshi/zhiyingdianzhanshi/" target="_blank">更多直营店</a></p>
                    </div>