<li class='col-2-1 last not-animated' data-animate='fadeInUp'>
                      <div class="article-list-row">
                        <ul>
                          <li><span class="float-right article-time"><strong>[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</strong></span><a class="article-title" href="[field:arcurl/]" target="_blank">[field:title/]</a></li>
                        </ul>
                      </div>
                    </li>
                    
                  </ul>
                </div>