<li class='col-3-1 not-animated' data-animate='fadeInUp'>
                      <div class="product-item">
                        <div class="portfolio-img"><a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" alt="[field:title/]"/></a></div>
                        <div class="portfolio-title">
                          <h2><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h2>
                        </div>
                      </div>
                    </li>