<div class="qhd-content">
                                <p style="text-align: center;"> <a href="[field:typelink /]" target="_blank"><img alt="" src="/style/images/join1.jpg" style="width: 509px; height: 339px;" /></a></p>
                                <p style="text-align: center;"> <a href="/[field:typelink /]" target="_blank"><span style="font-size:24px;">[field:typename /]</span><br />
                                  <span style="color:#d3d3d3;"><span style="line-height: 1.8;">THE JOIN CONDITIONS</span></span></a></p>
                              </div>