<?php
$z[0]=Array("arclist","\r\n                                  <li>\r\n                                    <p><a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/></a></p>\r\n                                    <h2><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></h2>\r\n                                  </li>\r\n                                  ",638,1053);
$z[0][4]['row']="9";
$z[0][4]['titlelen']="36";
$z[1]=Array("field","",1661,1682);
$z[1][4]['name']="typeurl";

?>