<?php
$z[0]=Array("global","",242,268);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","(@me==\"\")? @me=\" class='current'\":@me=\"\";",1744,1835);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channelartlist","\r\n            <li {dede:field name='currentstyle'/}><a class=\"first-level\" href=\"{dede:field name='typeurl'/}\" target=\"\"><strong>{dede:field name='typename'/}</strong></a><i></i>\r\n              <ul class=\"\">\r\n                {dede:channel type='son' noself='yes'}\r\n                <li class=\"\"><a class=\"\" href=\"[field:typelink/]\" target=\"\"><strong>[field:typename/]</strong></a></li>\r\n                {/dede:channel}\r\n              </ul>\r\n            </li>\r\n            ",1931,2465);
$z[2][4]['row']="10";
$z[2][4]['typeid']="top";

?>